<a href="https://colab.research.google.com/github/devpatel0005/Live-Covid-Cases-Tracker/blob/main/Live_Covid_Tracker.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Corona Virus Live Tracking For India

In [7]:
import pandas as pd

df = pd.read_json('https://covid19dashboard.mohfw.gov.in/data/datanew.json')
df

,sno,state_name,active,positive,cured,death,new_active,new_positive,new_cured,new_death,death_reconsille,total,state_code,actualdeath24hrs
0,1,Andhra Pradesh,102,231,129,0,101,241,140,0,,,28,0
1,2,Arunachal Pradesh,0,3,3,0,0,3,3,0,,,12,0
2,3,Assam,26,39,13,0,29,43,14,0,,,18,0
3,4,Bihar,41,93,52,0,38,98,60,0,,,10,0
4,5,Chandigarh,2,5,3,0,2,5,3,0,,,4,0
5,6,Chhattisgarh,50,99,49,0,50,105,55,0,,,22,0
6,7,Delhi,672,2640,1960,8,682,2814,2121,11,,3,7,3
7,8,Goa,6,25,19,0,6,25,19,0,,,30,0
8,9,Gujarat,1437,2603,1164,2,1441,2784,1341,2,,,24,0
9,10,Haryana,97,299,202,0,99,322,223,0,,,6,0
10,11,Himachal Pradesh,0,3,3,0,0,3,3,0,,,2,0
11,12,Jammu and Kashmir,9,23,14,0,17,33,16,0,,,1,0
12,13,Jharkhand,25,37,11,1,27,39,11,1,,,20,0
13,14,Karnataka,527,1705,1167,11,573,1756,1172,11,,,29,0
14,15,Kerala***,2109,6187,4055,23,2007,6457,4422,28,,5,32,5
15,16,Ladakh,3,3,0,0,4,4,0,0,,,37,0
16,17,Madhya Pradesh,120,169,46,3,130,185,52,3,,,23,0
17,18,Maharashtra,613,1914,1276,25,578,1967,1362,27,,2,27,2
18,19,Manipur,5,5,0,0,8,8,0,0,,,14,0
19,20,Mizoram,0,2,2,0,0,2,2,0,,,15,0
20,21,Odisha,45,90,45,0,50,99,49,0,,,21,0
21,22,Puducherry,10,113,103,0,10,114,104,0,,,34,0
22,23,Punjab,29,63,32,2,34,71,35,2,,,3,0
23,24,Rajasthan,180,376,194,2,192,397,203,2,,,8,0
24,25,Sikkim,50,95,45,0,57,110,53,0,,,11,0
25,26,Tamil Nadu,232,811,572,7,243,849,599,7,,,33,0
26,27,Telangana,8,21,13,0,9,23,14,0,,,36,0
27,28,Tripura,2,3,1,0,2,3,1,0,,,16,0
28,29,Uttarakhand,5,44,39,0,9,54,45,0,,,5,0
29,30,Uttar Pradesh,248,593,343,2,238,621,381,2,,,9,0
30,31,West Bengal,747,1160,412,1,747,1160,412,1,,,19,0
31,37,,7400,19454,11967,87,7383,20395,12915,97,,10,0,10